APP_NAME: otp-service
PORT: 8085

DB_NAME: otp_service
DB_HOST: localhost
DB_PORT: 5432
DB_DRIVER: postgres
DB_USER: postgres
DB_PASSWORD: pass123
DB_READ_TIMEOUT_IN_MS: 50
DB_WRITE_TIMEOUT_IN_MS: 200
DB_MAX_OPEN_CONNECTIONS: 10
DB_MAX_IDLE_CONNECTIONS: 10

LOG_LEVEL: info
LOG_FORMAT: json
